name: elifbauygulamasi
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.18
  intl_phone_number_input: ^0.7.2
  google_sign_in:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  toast:
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite:
  path:


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints:
  responsive_framework:
  mailer:
  flutter_email_sender:
  flutter_advanced_drawer:
  audioplayers:
  image_picker:
  file_picker:
  permission_handler:
  path_provider:
  sqflite_common_ffi:
  flutter_custom_cards:
  flutter_animated_button:
  social_login_buttons:
  google_fonts:
  flare_flutter:
  animated_icon_button:
  charts_flutter:



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/topImage.png
      - assets/images/baykus.png
      - assets/images/erkek.png
      - assets/images/kuran.png
      - assets/images/kız.jpg
      - assets/images/kuranokuyoncocuklar.jpg
      - assets/images/morkız.jpg
      - assets/images/kurann.png
      - assets/images/google.png
      - assets/images/beyaz.png
      - assets/images/1.png
      - assets/images/2.png
      - assets/images/balon.jpg
      - assets/images/ucan.jpg
      - assets/images/ucak2.jpg
      - assets/images/baloniki.jpg
      - assets/images/renkli.jpg
      - assets/images/sade.jpg
      - assets/resim/n.png
      - assets/resim/kitap.png
      - assets/resim/1.png
      - assets/resim/2.png
      - assets/resim/3.png
      -  assets/resim/ses.jpg
      - assets/resim/Elif-Ba.png
      - assets/resim/eLİFBA.png
      - assets/resim/Elif-Baa.png
      - assets/resim/arkaplan.jpg
      - assets/resim/dersarkaplan.jpg
      - assets/harfyazi/ELİF.png
      - assets/resim/Elif.png
      - assets/resim/eliff.png
      - assets/elifba/ayın.png
      - assets/elifba/be.png
      - assets/elifba/cim.png
      - assets/elifba/dad.png
      - assets/elifba/dal.png
      - assets/elifba/elif.png
      - assets/elifba/fe.png
      - assets/elifba/gaf.png
      - assets/elifba/ha.png
      - assets/elifba/he.png
      - assets/elifba/kef.png
      - assets/elifba/lam.png
      - assets/elifba/lamelif.jpg
      - assets/elifba/mim.png
      - assets/elifba/nun.png
      - assets/elifba/peltekSe.png
      - assets/elifba/ra.png
      - assets/elifba/sad.png
      - assets/elifba/sin.png
      - assets/elifba/ta.png
      - assets/elifba/te.png
      - assets/elifba/vav.png
      - assets/elifba/ye.png
      - assets/elifba/za.png
      - assets/elifba/ze.png
      - assets/elifba/zel.png
      - assets/elifba/ğayn.png
      - assets/elifba/ğhı.png
      - assets/elifba/şin.png
      - assets/elifba/ustun/ayın_üstün.png
      - assets/elifba/ustun/be_üstün.png
      - assets/elifba/ustun/cim_üstün.png
      - assets/elifba/ustun/dad_üstün.png
      - assets/elifba/ustun/dal_üstün.png
      - assets/elifba/ustun/elif_üstün.png
      - assets/elifba/ustun/fe_üstün.png
      - assets/elifba/ustun/gaf_üstün.png
      - assets/elifba/ustun/gayın_üstün.png
      - assets/elifba/ustun/ha_üstün.png
      - assets/elifba/ustun/he_üstün.png
      - assets/elifba/ustun/hı_üstün.png
      - assets/elifba/ustun/kef_üstün.png
      - assets/elifba/ustun/lam_üstün.png
      - assets/elifba/ustun/mim_üstün.png
      - assets/elifba/ustun/nun_üstün.png
      - assets/elifba/ustun/ra_üstün.png
      - assets/elifba/ustun/sad_üstün.png
      - assets/elifba/ustun/se_üstün.png
      - assets/elifba/ustun/sin_üstün.png
      - assets/elifba/ustun/te_üstün.png
      - assets/elifba/ustun/tı_üstün.png
      - assets/elifba/ustun/vav_üstün.png
      - assets/elifba/ustun/ye_üstün.png
      - assets/elifba/ustun/ze_üstün.png
      - assets/elifba/ustun/zel_üstün.png
      - assets/elifba/ustun/zı_üstün.png
      - assets/elifba/ustun/şin_üstün.png
      - assets/elifba/esre/ayın_esre.png
      - assets/elifba/esre/be_esre.png
      - assets/elifba/esre/cim_esre.png
      - assets/elifba/esre/dad_esre.png
      - assets/elifba/esre/dal_esre.png
      - assets/elifba/esre/elif_esre.png
      - assets/elifba/esre/fe_esre.png
      - assets/elifba/esre/gaf_esre.png
      - assets/elifba/esre/gayın_esre.png
      - assets/elifba/esre/ha_esre.png
      - assets/elifba/esre/he_esre.png
      - assets/elifba/esre/hı_esre.png
      - assets/elifba/esre/kef_esre.png
      - assets/elifba/esre/lam_esre.png
      - assets/elifba/esre/mim_esre.png
      - assets/elifba/esre/nun_esre.png
      - assets/elifba/esre/ra_esre.png
      - assets/elifba/esre/sad_esre.png
      - assets/elifba/esre/se_esre.png
      - assets/elifba/esre/sin_esre.png
      - assets/elifba/esre/te_esre.png
      - assets/elifba/esre/tı_esre.png
      - assets/elifba/esre/vav_esre.png
      - assets/elifba/esre/ye_esre.png
      - assets/elifba/esre/ze_esre.png
      - assets/elifba/esre/zel_esre.png
      - assets/elifba/esre/zı_esre.png
      - assets/elifba/esre/şin_esre.png
      - assets/elifba/otre/ayın_ötre.png
      - assets/elifba/otre/be_ötre.png
      - assets/elifba/otre/cim_ötre.png
      - assets/elifba/otre/dad_ötre.png
      - assets/elifba/otre/dal_ötre.png
      - assets/elifba/otre/elif_ötre.png
      - assets/elifba/otre/fe_ötre.png
      - assets/elifba/otre/gaf_ötre.png
      - assets/elifba/otre/gayın_ötre.png
      - assets/elifba/otre/ha_ötre.png
      - assets/elifba/otre/he_ötre.png
      - assets/elifba/otre/hı_ötre.png
      - assets/elifba/otre/kef_ötre.png
      - assets/elifba/otre/lam_ötre.png
      - assets/elifba/otre/mim_ötre.png
      - assets/elifba/otre/nun_ötre.png
      - assets/elifba/otre/ra_ötre.png
      - assets/elifba/otre/sad_ötre.png
      - assets/elifba/otre/se_ötre.png
      - assets/elifba/otre/sin_ötre.png
      - assets/elifba/otre/te_ötre.png
      - assets/elifba/otre/tı_ötre.png
      - assets/elifba/otre/vav_ötre.png
      - assets/elifba/otre/ye_ötre.png
      - assets/elifba/otre/ze_ötre.png
      - assets/elifba/otre/zel_ötre.png
      - assets/elifba/otre/zı_ötre.png
      - assets/elifba/otre/şin_ötre.png


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
  #  - family: Comic Neue
  #    fonts:
  #      - asset: yazitipi/ComicNeue-Regular.ttf
  #      - asset: yazitipi/ComicNeue-Italic.ttf
  #      - asset: yazitipi/ComicNeue-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
